################################################################################
# Reusable build workflow
################################################################################

name: Build

on:
  workflow_call:
    inputs:
      arch:
        description: Either x86 or x64
        required: true
        type: string
      type:
        description: CMake build type
        required: true
        type: string

jobs:
  windows_msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{ inputs.arch }}

      - name: Configure
        run: cmake -S . -B Build

      - name: Build
        run: cmake --build Build --config ${{ inputs.type }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: c1-launcher-${{ inputs.arch }}
          path: |
            ${{ github.workspace }}\Build\${{ inputs.type }}\*.exe
            ${{ github.workspace }}\Build\${{ inputs.type }}\*.pdb
